try fix to pipeline

diff --git a/.github/workflows/development.yml b/.github/workflows/development.yml
--- a/.github/workflows/development.yml
+++ b/.github/workflows/development.yml
@@ -1,46 +1,101 @@
-name: DevelopmentPipeline
+name: Publish Develop to GitHub Pages
 
-on: 
-  push: 
-    branches: [develop]
+on:
+  push:
+    branches: ["main"]
 
-jobs: 
+env:
+  NODE_AUTH_TOKEN: ${{ secrets.PAGES_DEPLOYMENT }}
+
+permissions:
+  contents: read
+  pages: write
+  id-token: write
+
+concurrency:
+  group: "pages"
+  cancel-in-progress: true
+
+jobs:
+  #Build Job
+  build:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout 🛎️
+        uses: actions/checkout@v3
+      - name: Detect package manager 👻
+        id: detect-package-manager
+        run: |
+          if [ -f "${{ github.workspace }}/yarn.lock" ]; then
+            echo "::set-output name=manager::yarn"
+            echo "::set-output name=command::install"
+            echo "::set-output name=runner::yarn"
+            exit 0
+          elif [ -f "${{ github.workspace }}/package.json" ]; then
+            echo "::set-output name=manager::npm"
+            echo "::set-output name=command::ci"
+            echo "::set-output name=runner::npx --no-install"
+            exit 0
+          else
+            echo "Unable to determine packager manager"
+            exit 1
+          fi
+      - name: Setup Node 🍉
+        uses: actions/setup-node@v3
+        with:
+          cache: ${{ steps.detect-package-manager.outputs.manager }}
+          node-version: '18.14.2'
+
+      - name: Setup Pages 🔧
+        id: pages
+        uses: actions/configure-pages@v1
+        with:
+          # Automatically inject basePath in your Next.js configuration file and disable
+          # server side image optimization (https://nextjs.org/docs/api-reference/next/image#unoptimized).
+          #
+          # You may remove this line if you want to manage the configuration yourself.
+          static_site_generator: next
+      - name: Restore cache 💾
+        uses: actions/cache@v3
+        with:
+          path: |
+            .next/cache
+          # Generate a new cache whenever packages or source files change.
+          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
+          # If source files changed but packages didn't, rebuild from a prior cache.
+          restore-keys: |
+            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json', '**/yarn.lock') }}-
+      - name: Install dependencies 🥑
+        run: ${{ steps.detect-package-manager.outputs.manager }} ${{ steps.detect-package-manager.outputs.command }}
+      - name: Build with Next.js 🍄
+        run: ${{ steps.detect-package-manager.outputs.runner }} next build
+      - name: Static HTML export with Next.js 🥯
+        run: ${{ steps.detect-package-manager.outputs.runner }} next export
+      - name: Upload artifact ⛱️
+        uses: actions/upload-pages-artifact@v1
+        with:
+          path: ./out
+
+  #Lint Job
   lintTest:
     name: Lint
     runs-on: ubuntu-latest
-    steps: 
-      - name: Clone Repository
-        uses: actions/checkout@v2
-      - name: Install Dependencies
-        run: |
-          echo "Running Install Dependencies ..."
-          npm install
-      - name: Run Linter
-        run: |
-          echo "Running Linting tests ..."
-          npm run lint
+      steps: 
+        - name: Run Linter
+          run: |
+             echo "Running Linting tests ..."
+             npm run lint
         env:
           CI: true
-  securityCheck:
-    name: Security Check
-    runs-on: ubuntu-latest
-    steps: 
-      - name: Check for Security
-        run: |
-        echo "Running Security Checks ..."
-        sleep 5s;
-        echo "Running Security Checks ... 1"
-        sleep 5s;
-        echo "Running Security Checks ... 2"
-        sleep 5s;
-        echo "Running Security Checks ... 3"
-         
-  deploy:
-    name: Deployment
-    runs-on: ubuntu-latest
-    needs: [lintTest, securityCheck]
-    steps: 
-      - name: Deploying app
-        run: |
-          echo "Deployment in progress ..."
 
+  # Deployment job
+  deploy:
+    environment:
+      name: github-pages
+      url: ${{ steps.deployment.outputs.page_url }}
+    runs-on: ubuntu-latest
+    needs: build
+    steps:
+      - name: Deploy to GitHub Pages 🚀
+        id: deployment
+        uses: actions/deploy-pages@v1
